version: "3"

services:

  scylla-node1:
    image: scylladb/scylla:4.1.0
    restart: always
    command: --seeds=18.10.0.21,18.10.0.22 --listen-address=18.10.0.21 --rpc-address=18.10.0.21 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --developer-mode 1
    volumes:
      - "./configurations/Node_1/scylla-staticIP.yaml:/etc/scylla/scylla.yaml"
      - "./configurations/Datacenter1_properties/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      scylla_network2:
        ipv4_address: 18.10.0.21
      

  scylla-node2:
    image: scylladb/scylla:4.1.0
    restart: always
    command: --seeds=18.10.0.21,18.10.0.22 --listen-address=18.10.0.22 --rpc-address=18.10.0.22 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --developer-mode 1
    volumes:
      - "./configurations/Node_2/scylla-staticIP.yaml:/etc/scylla/scylla.yaml"
      - "./configurations/Datacenter1_properties/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      scylla_network2:
        ipv4_address: 18.10.0.22

  scylla-node3:
    image: scylladb/scylla:4.1.0
    restart: always
    command: --seeds=18.10.0.21,18.10.0.22 --listen-address=18.10.0.23 --rpc-address=18.10.0.23 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --developer-mode 1
    volumes:
      - "./configurations/Node_3/scylla-staticIP.yaml:/etc/scylla/scylla.yaml"
      - "./configurations/Datacenter1_properties/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      scylla_network2:
        ipv4_address: 18.10.0.23
  
  scylla-node4:
    image: scylladb/scylla:4.1.0
    restart: always
    command: --seeds=18.10.0.21,18.10.0.22 --listen-address=18.10.0.24 --rpc-address=18.10.0.24 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --developer-mode 1
    volumes:
      - "./configurations/Node_4/scylla-staticIP.yaml:/etc/scylla/scylla.yaml"
      - "./configurations/Datacenter1_properties/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      scylla_network2:
        ipv4_address: 18.10.0.24      
    
# Manually configuring network for the nodes using not assigning an existing one.
# Below are the configuratios to be done.
networks:
  scylla_network2:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 18.10.0.0/16
